// Generated by Wrangler on Sun Aug 11 2024 08:09:03 GMT+0800 (China Standard Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	sub: KVNamespace;
	TG_BOT_TOKEN: string;
}
