// Generated by Wrangler on Mon May 20 2024 23:28:41 GMT+0800 (China Standard Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	BOT_TOKEN: string;
	IPAPI_IS_KEY: string;
	MY_CHAT_ID: string;
	MY_SUB_URLS: string;
	MY_UUID: string;
	PROXYCHECK_IO_KEY: string;
}
