#:schema node_modules/wrangler/config-schema.json
name = "api"
main = "src/index.ts"
compatibility_date = "2024-09-03"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "sub"
id = "8b5259fc13f94d85bc4c7bc316198fa1"
