#:schema https://www.unpkg.com/wrangler/config-schema.json

compatibility_date = "2025-05-31"
compatibility_flags = ["nodejs_compat"]
main = "./src/index.ts"
minify = true
name = "api"
send_metrics = false
upload_source_maps = true

[[kv_namespaces]]
binding = "KV"
id = "9ee893b26f644ffa8310b02483aa9934"

[observability]
enabled = true
