#:schema https://www.unpkg.com/wrangler/config-schema.json

name = "api"
main = "./src/index.ts"
compatibility_date = "2025-05-31"
compatibility_flags = ["nodejs_compat"]
minify = true

[observability]
enabled = true
