// Generated by Wrangler on Sat Sep 07 2024 13:08:50 GMT+0800 (China Standard Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
  sub: KVNamespace
  TG_BOT_TOKEN: string
}
